@echo off
@title = Windows 7 - Clear Temp files
SET /P pcname="Please enter the computer name or IP address"
echo please wait...
echo Connecting to remote system.
net use X: "\\%pcname%\C$"
cd /d "X:\users"
echo clearing temp files...
echo please wait...
for /d %%a in (*) do del /F /s /q "c:\users\%%a\AppData\Local\Temp" >nul 2>&1
echo clearing temporary internet files...
echo please wait...
for /d %%a in (*) do del /F /s /q "c:\users\%%a\AppData\Local\Microsoft\Windows\Temporary Internet Files" >nul 2>&1
echo clearing temp program files...
echo please wait...
cd /d "X:\Windows\Downloaded Program Files"
del *.* /F /s /q
echo clearing temp windows update files...
echo please wait...
cd /d "X:\Windows\SoftwareDistribution\Download"
del *.* /F /s /q
echo all temp files cleared.
exit