#! /bin/bash

read -r -p 'enter sudo password: ' supwd # prompt user for sudo password
echo $supwd | sudo -S apt-get update
echo Grabbing updates...
echo Please stand by...
sudo apt-get -y upgrade
echo updating....
echo Please stand by...